// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/curral-header/Current.tsx": () => import("../components/mockups/curral-header/Current.tsx"),
  "./components/mockups/radar-tv/RadarTv.tsx": () => import("../components/mockups/radar-tv/RadarTv.tsx")
};
